# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDH5rcXs8dlmTjmpwlLlymPQjKsCW15P
"""

import pandas as pd
data = pd.read_excel('Student_data.xlsx')
print(data.head())

import matplotlib.pyplot as plt

# Check correlation
print(data.corr())

# Visualization: Study Hours vs Final Result
plt.scatter(data['study_Hours'], data['Final_result'])
plt.xlabel('study Hours')
plt.ylabel('Final result')
plt.title('study Hours vs Student Performance')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = data[['Attendance','study_Hours','previous_Grade','Assignments','Particiption']]
y = data['Final_result']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Predicted Values:", pred)

from google.colab import drive
drive.mount('/content/drive')

!cp /content/student_data.xlsx /content/drive/MyDrive/

# Commented out IPython magic to ensure Python compatibility.
# %save /content/drive/MyDrive/Student_Performance_Project.ipynb